version: '3'

services:
  traefik:
    restart: always
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true

# docker network create traefik-network
